### PR TITLE
Copy button functional! Needs styling.

### PR DESCRIPTION
**Pull request by SIGSTACKFAULT**
Working on it.

### CODE REVIEW

**Review by choraria — COMMENTED** [review]
@SIGSTACKFAULT - thanks for pitching in. I'm terribly bad at CSS (front-end to be precise 😅).

But I bet the community would build on from here and I'll merge this PR soon as its finished.

**Comment by saxobroko** [comment]
Add "return 'Link Copied To Clipboard';"
i've tried adding this but I get errors everytime

**Comment by saxobroko** [comment]
I have done some styling but I can't find a way to add it here. [Live Preview](https://saxob.ga)
`<style>.copy:hover {background-color: #000;}.copy{font-family: 'Open Sans', sans-serif; background-color: #555555;border: none;color: white;padding: 15px 32px;text-align: center;text-decoration: none;display: inline-block;font-size: 16px;margin: 4px 2px;cursor: pointer;}</style>`
I also made a change with line 59, I added a line break and i capitalised 'Copy'
`element.innerHTML = (lastURL + '<br /><button class="copy" onclick="clip()">Copy</button>');`

**Review by saxobroko — APPROVED** [review]

**Comment by choraria** [comment]
@saxobroko - thanks a ton for your interest in this :)

I see that its currently a copy "box"; let me work on this over the following week to see if I can get a little creative and get an icon to do this job!

Will keep this open, for now.

**Comment by SIGSTACKFAULT** [comment]
@schoraria911 https://thenounproject.com/ has icons, licensed for free with credit or for like $2 without credit.

**Comment by choraria** [comment]
> @schoraria911 https://thenounproject.com/ has icons, licensed for free with credit or for like $2 without credit.

@SIGSTACKFAULT - my idea was to pick it up from Materialize CSS itself :)
https://materializecss.com/icons.html
Icon name: content_copy

**Pull request closed without merging**
